version: '2'
services:
  dev:
    image : demoformationapi_dev-${PHPVERSION}:latest 
    network_mode: bridge
    hostname: dev-5.6
    ports:
     - "8080:80"
    depends_on:
     - redis
    links:
     - redis
    volumes:
     - .:/var/www
  redis:
    image: redis
    network_mode: bridge
    hostname: redis
    ports:
        - "6379:6379"
    restart: always
