version: '2'
services:
  demoapi-5.6:
    build:
      context: .
      dockerfile: Dockerfile-dev-5.6
    image: interact-iv/demoapi-php5.6:latest
    network_mode: bridge
    hostname: dev-5.6 
    ports:
     - "8080:80"
    depends_on:
     - redis
     - mysql
    links:
     - redis
     - mysql
    volumes:
     - .:/var/www
    environment:
      - RESET_DB=${RESET_DB}
  redis:
    image: redis
    network_mode: bridge
    hostname: redis
    ports:
        - "6379:6379"
    restart: always
  mysql:
    image: mysql:latest
    network_mode: bridge
    hostname: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
